# This file is the main config file for your service.
# For full config options, check the docs:
#    docs.serverless.com

service: GazetteMachine

plugins:
  - serverless-plugin-existing-s3
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.7
  region: eu-west-1
  profile: lawsafrica
  stage: production
  environment:
    API_AUTH_TOKEN: ${ssm:GazetteMachine-API-auth-token}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ecs:RunTask"
      Resource:
        - "arn:aws:ecs:eu-west-1:254881051502:task-definition/*"
    - Effect: "Allow"
      Action:
        - "iam:PassRole"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "s3:PutBucketNotification"
      Resource:
        - "arn:aws:s3:::lawsafrica-gazettes-incoming"

package:
  exclude:
    - "./**"
  include:
    - service.py
    - gm/__init__.py
    - gm/gm.py

functions:
  ArchiveGazette:
    handler: service.identify_and_archive
    events:
      - http:
          path: archive-gazette
          method: post

  IncomingFromS3:
    handler: service.incoming_from_s3
    events:
      - existingS3:
          bucket: lawsafrica-gazettes-incoming
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: dropbox/
