# This file is the main config file for your service.
# For full config options, check the docs:
#    docs.serverless.com

service: GazetteMachine

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  profile: lawsafrica
  stage: production
  timeout: 30
  environment:
    API_AUTH_TOKEN: ${ssm:GazetteMachine-API-auth-token}
    MIRROR_TARGETS: ${ssm:GazetteMachine-mirror-targets}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutBucketNotification"
      Resource:
        - "arn:aws:s3:::lawsafrica-gazettes-archive"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::lawsafrica-gazettes-archive"
        - "arn:aws:s3:::lawsafrica-gazettes-archive/*"
  tracing:
    lambda: true

package:
  exclude:
    - "./**"
  include:
    - service.py

custom:
  pythonRequirements:
    slim: true

functions:
  ArchivedGazetteChanged:
    handler: service.archived_gazette_changed
    events:
      - s3:
        bucket: lawsafrica-gazettes-archive
        event: s3:ObjectCreated:*
        rules:
          - prefix: archive/
        existing: true
      - s3:
        bucket: lawsafrica-gazettes-archive
        event: s3:ObjectRemoved:*
        rules:
          - prefix: archive/
        existing: true
