# This file is the main config file for your service.
# For full config options, check the docs:
#    docs.serverless.com

service: GazetteMachine

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.7
  region: eu-west-1
  profile: lawsafrica
  stage: production
  environment:
    API_AUTH_TOKEN: ${ssm:GazetteMachine-API-auth-token}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutBucketNotification"
      Resource:
        - "arn:aws:s3:::lawsafrica-gazettes-incoming"
        - "arn:aws:s3:::lawsafrica-gazettes-archive"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:DeleteObject"
      Resource:
        - "arn:aws:s3:::lawsafrica-gazettes-incoming"
        - "arn:aws:s3:::lawsafrica-gazettes-incoming/*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::lawsafrica-gazettes-archive"
        - "arn:aws:s3:::lawsafrica-gazettes-archive/*"

package:
  exclude:
    - "./**"
  include:
    - service.py

functions:
  IncomingFromS3:
    handler: service.incoming_from_s3
    events:
      - s3:
        bucket: lawsafrica-gazettes-incoming
        existing: true
        events:
          - s3:ObjectCreated:*
        rules:
          - prefix: dropbox/
  ArchivedGazetteChanged:
    handler: service.archived_gazette_changed
    events:
      - s3:
        bucket: lawsafrica-gazettes-archive
        events:
          - s3:ObjectCreated:*
          - s3:ObjectRemoved:*
        rules:
          - prefix: archive/
        existing: true
